//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConsoleConsumer.DayOfWeekConsumer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfWeekConsumer.IDayOfWeekProviderService")]
    public interface IDayOfWeekProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekProviderService/GetDate", ReplyAction="http://tempuri.org/IDayOfWeekProviderService/GetDateResponse")]
        string GetDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekProviderService/GetDate", ReplyAction="http://tempuri.org/IDayOfWeekProviderService/GetDateResponse")]
        System.Threading.Tasks.Task<string> GetDateAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfWeekProviderServiceChannel : ServiceConsoleConsumer.DayOfWeekConsumer.IDayOfWeekProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfWeekProviderServiceClient : System.ServiceModel.ClientBase<ServiceConsoleConsumer.DayOfWeekConsumer.IDayOfWeekProviderService>, ServiceConsoleConsumer.DayOfWeekConsumer.IDayOfWeekProviderService {
        
        public DayOfWeekProviderServiceClient() {
        }
        
        public DayOfWeekProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfWeekProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDate(System.DateTime date) {
            return base.Channel.GetDate(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDateAsync(System.DateTime date) {
            return base.Channel.GetDateAsync(date);
        }
    }
}
