//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringsOperatorConsoleClient.StringsOperatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringsOperatorService.IStringsOperator")]
    public interface IStringsOperator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsOperator/GetCountFStringContainsSecond", ReplyAction="http://tempuri.org/IStringsOperator/GetCountFStringContainsSecondResponse")]
        int GetCountFStringContainsSecond(string str1, string str2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsOperator/GetCountFStringContainsSecond", ReplyAction="http://tempuri.org/IStringsOperator/GetCountFStringContainsSecondResponse")]
        System.Threading.Tasks.Task<int> GetCountFStringContainsSecondAsync(string str1, string str2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringsOperatorChannel : StringsOperatorConsoleClient.StringsOperatorService.IStringsOperator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringsOperatorClient : System.ServiceModel.ClientBase<StringsOperatorConsoleClient.StringsOperatorService.IStringsOperator>, StringsOperatorConsoleClient.StringsOperatorService.IStringsOperator {
        
        public StringsOperatorClient() {
        }
        
        public StringsOperatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringsOperatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsOperatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsOperatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCountFStringContainsSecond(string str1, string str2) {
            return base.Channel.GetCountFStringContainsSecond(str1, str2);
        }
        
        public System.Threading.Tasks.Task<int> GetCountFStringContainsSecondAsync(string str1, string str2) {
            return base.Channel.GetCountFStringContainsSecondAsync(str1, str2);
        }
    }
}
